apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: nlokeshbabu/my-python: {{ .Values.image.tag }}
        ports:
        - containerPort: 5000

